version: "3.6"
services:
  ui:
    build:
      context: ./ui
      dockerfile: ./build/Dockerfile
    ports:
      - "8080:80"
  api:
    build:
      context: ./api
      dockerfile: ./build/Dockerfile
    ports:
      - "4000:4000"
